import {test} from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {project,unproject,prepareMap,clipPolygon,nearestRoad} from '../src/austin.js';
const data=JSON.parse(readFileSync(new URL('../public/assets/austin/map.json',import.meta.url)));const map=prepareMap(structuredClone(data));
test('Austin map contains real Congress Avenue, Sixth Street and Capitol footprints',()=>{assert.ok(data.roads.some(r=>r.name==='Congress Avenue'));assert.ok(data.roads.some(r=>r.name==='East 6th Street'));assert.ok(data.buildings.some(b=>b.name==='Texas State Capitol'));assert.ok(data.areas.some(a=>a.name==='Lady Bird Lake'));});
test('coordinate projection uses meters and round trips correctly',()=>{const p=project(data.origin.lon,data.origin.lat,data.origin);assert.deepEqual(p,{x:0,z:-0});const ll=unproject(100,-100,data.origin);const xy=project(ll.lon,ll.lat,data.origin);assert.ok(Math.abs(xy.x-100)<1e-6&&Math.abs(xy.z+100)<1e-6);});
test('spawn is on Congress Avenue and outside buildings or water',()=>{assert.equal(map.collider.blocked(map.spawn.x,map.spawn.z),false);assert.equal(nearestRoad(map.spawn.x,map.spawn.z,map.lines).road.name,'Congress Avenue');});
test('polygons are clipped to playable map boundaries',()=>{assert.deepEqual(clipPolygon([[-5,-5],[5,-5],[5,5],[-5,5]],{minX:-1,maxX:1,minZ:-1,maxZ:1}).length,4);});
test('crossing a bridge edge resolves locally instead of teleporting to shore',()=>{const bridge=map.lines.find(s=>s.road.bridge&&s.road.name==='South Congress Avenue'&&s.length>200);assert.ok(bridge);const ux=(bridge.b[0]-bridge.a[0])/bridge.length,uz=(bridge.b[1]-bridge.a[1])/bridge.length,x=(bridge.a[0]+bridge.b[0])/2-uz*(bridge.road.width/2+.01),z=(bridge.a[1]+bridge.b[1])/2+ux*(bridge.road.width/2+.01);const contacts=map.collider.contacts(x,z);assert.ok(contacts.length);assert.ok(Math.max(...contacts.map(c=>c.depth))<1,'bridge edge must not eject player to a distant riverbank');});

test('map retains real street furniture, trees and named places',()=>{for(const kind of ['tree','bench','street_lamp','traffic_signals','crossing','fountain','poi'])assert.ok(data.features.some(f=>f.kind===kind),kind);assert.ok(data.features.some(f=>f.name==='Stevie Ray Vaughan Statue'));assert.ok(data.roads.some(r=>r.surface==='compacted'));});
test('road surfaces and raised sidewalks are queried from the same geometry',()=>{const s=map.lines.find(s=>s.road.name==='Congress Avenue'&&s.length>40);const x=(s.a[0]+s.b[0])/2,z=(s.a[1]+s.b[1])/2;assert.equal(map.terrain(x,z).kind,'asphalt');assert.equal(map.collider.surface(x,z,0),0);assert.ok(map.features.filter(f=>f.kind==='tree').some(f=>map.terrain(f.x,f.z).kind==='grass'));});

test('generated streetscape is identified separately and stays off roads',()=>{const generated=map.features.filter(f=>f.generated);assert.ok(generated.length>20);assert.equal(map.mappedFeatureCount,data.features.length);for(const f of generated){assert.equal(map.terrain(f.x,f.z).kind,'sidewalk');assert.equal(map.buildingCollider.blocked(f.x,f.z),false);}});
