import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createWorld,stepWorld,createCollider,cameraClearance,hitTraffic,collectEnergy,GRAVITY,RUN_SPEED,BOOST_SPEED,updateView} from '../src/game.js';
const empty=createCollider([]);
function running(){const s=createWorld();s.status='running';return s;}
function advance(s,input,seconds=1,collider=empty){for(let t=0;t<seconds-1e-8;t+=1/120)stepWorld(s,input,1/120,collider);}
const wall=createCollider([{polygon:[[20,-30],[24,-30],[24,30],[20,30]],height:15}]);
test('acceleration is finite and momentum continues during braking',()=>{const s=running();advance(s,{forward:true},1);assert.ok(s.speed>10&&s.speed<50);const z=s.z;advance(s,{},.1);assert.ok(s.z<z);assert.ok(s.speed>0);advance(s,{},2);assert.ok(s.speed<.01);});
test('reversing brakes momentum before changing direction',()=>{const s=running();advance(s,{forward:true},2);stepWorld(s,{backward:true},1/120,empty);assert.ok(s.vz<0);advance(s,{backward:true},3);assert.ok(s.vz>0);});
test('turning does not instantly snap the velocity direction',()=>{const s=running();advance(s,{forward:true},2);stepWorld(s,{right:true},.05,empty);assert.ok(s.vz< -20);assert.ok(s.vx>10&&s.vx<s.speed*.8);});
test('all movement directions and arbitrary view angles work',()=>{for(const [input,axis,sign] of [[{right:true},'x',1],[{left:true},'x',-1],[{forward:true},'z',-1],[{backward:true},'z',1]]){const s=running();advance(s,input,2);assert.ok(s[axis]*sign>20);}const d=running();advance(d,{forward:true,viewYaw:Math.PI/4},1);assert.ok(Math.abs(d.x+d.z)<.001);});
test('gravity and ballistic jump match the expected jump apex',()=>{assert.equal(GRAVITY,9.81);const s=running();stepWorld(s,{jump:true},1/120,empty);let top=s.y;for(let i=0;i<240;i++){stepWorld(s,{},1/120,empty);top=Math.max(top,s.y);}assert.ok(top>2.2&&top<2.5);assert.equal(s.y,0);assert.equal(s.grounded,true);});
test('airborne steering is weaker than grounded steering',()=>{const a=running(),b=running();a.y=10;a.grounded=false;advance(a,{right:true},.2);advance(b,{right:true},.2);assert.ok(a.vx<b.vx*.4);});
test('diagonal speed is normalized and boost retains superhero top speed',()=>{const a=running(),b=running();advance(a,{forward:true},4);advance(b,{forward:true,right:true},4);assert.ok(Math.abs(a.speed-b.speed)<.01);assert.ok(a.speed<=RUN_SPEED+.01);const boost=running();advance(boost,{forward:true,boost:true},3);assert.ok(boost.speed>RUN_SPEED*2);assert.ok(boost.speed<=BOOST_SPEED+.01);});
test('polygon collisions prevent tunneling and remove wall-normal velocity',()=>{const s=running();s.vx=260;stepWorld(s,{right:true,boost:true},.2,wall);assert.ok(s.x<20);assert.ok(s.vx<1);assert.equal(wall.blocked(s.x,s.z),false);});
test('glancing collision preserves tangential motion',()=>{const s=running();s.x=19;s.vx=80;s.vz=30;stepWorld(s,{},.03,wall);assert.ok(s.x<20);assert.ok(s.z>0);assert.ok(s.vz>0);});
test('camera clearance follows actual polygon map',()=>{assert.ok(cameraClearance(19,0,11,0,wall)<.1);assert.equal(cameraClearance(0,0,0,10,wall),1);});
test('paused state is unchanged and there are no race limits',()=>{const s=running();s.status='paused';const before=structuredClone(s);advance(s,{forward:true},1);assert.deepEqual(s,before);s.status='running';advance(s,{forward:true},65);assert.equal(s.status,'running');assert.ok(s.distance>4000);});
test('arrow view controls change yaw/pitch without moving the character',()=>{const v=updateView({yaw:0,pitch:.35},{right:true,up:true},1);assert.ok(v.yaw>0);assert.ok(v.pitch>.35);const clamped=updateView(v,{up:true},10);assert.ok(clamped.pitch<=1.15);});
test('traffic impulse and energy collection are bounded',()=>{const s=running();s.vx=50;assert.equal(hitTraffic(s,{x:1,z:0,vx:0,vz:0}),true);assert.ok(s.vx<50);assert.equal(hitTraffic(s),false);s.energy=99;collectEnergy(s);assert.equal(s.energy,100);});

test('phasing crosses buildings and ignores traffic',()=>{const s=running();s.vx=80;advance(s,{right:true,phase:true},.4,wall);assert.ok(s.x>24);assert.equal(s.phasing,true);assert.equal(hitTraffic(s),false);});
test('releasing phase inside a building restores a clear position',()=>{const s=running();s.x=19;s.vx=25;advance(s,{right:true,phase:true},.1,wall);assert.ok(s.x>20&&s.x<24);stepWorld(s,{},1/120,wall);assert.equal(s.phasing,false);assert.equal(wall.blocked(s.x,s.z,s.y),false);});
test('phase does not cross map boundaries',()=>{const s=running();const bounds=createCollider([],{minX:-5,maxX:5,minZ:-5,maxZ:5});advance(s,{right:true,phase:true},1,bounds);assert.ok(s.x<5);});
test('fast airborne approach starts a wall run, grounded and slow approaches do not',()=>{const s=running();s.x=18;s.vx=45;s.y=1;s.grounded=false;advance(s,{right:true},.1,wall);assert.ok(s.wallRunning);assert.ok(s.y>1);assert.equal(s.impact,0);for(const airborne of [false,true]){const b=running();b.x=19.5;b.vx=airborne?2:45;b.y=airborne?1:0;b.grounded=!airborne;advance(b,{right:true},.1,wall);assert.equal(b.wallRunning,false);}});
test('jump pushes away from wall and prevents immediate reattachment',()=>{const s=running();s.x=18;s.vx=45;s.y=1;s.grounded=false;advance(s,{right:true},.1,wall);stepWorld(s,{right:true,jump:true},1/120,wall);assert.equal(s.wallRunning,false);assert.ok(s.vx<0);assert.ok(s.vy>0);});
test('wall running crests onto a supported rooftop',()=>{const s=running();s.x=18;s.vx=45;s.y=1;s.grounded=false;let reached=false;for(let i=0;i<300;i++){stepWorld(s,{right:true},1/120,wall);if(s.grounded&&s.y===15){reached=true;break;}}assert.ok(reached);assert.ok(s.x>20);stepWorld(s,{},1/120,wall);assert.equal(s.y,15);});

test('walking off a roof resumes gravity',()=>{const s=running();s.x=23.8;s.y=15;s.vx=10;advance(s,{right:true},.2,wall);assert.equal(s.grounded,false);assert.ok(s.y<15);});
test('releasing movement detaches from the wall',()=>{const s=running();s.x=18;s.vx=45;s.y=1;s.grounded=false;advance(s,{right:true},.1,wall);stepWorld(s,{},1/120,wall);assert.equal(s.wallRunning,false);assert.equal(s.grounded,false);});

test('high-speed steering turns ninety degrees quickly without snapping',()=>{const s=running();s.vz=-90;s.speed=90;stepWorld(s,{right:true},1/120);assert.ok(s.vx>0&&s.vz< -50);advance(s,{right:true},.18);assert.ok(Math.abs(s.vz)<s.vx*.12,'turn should settle within 200 ms');assert.ok(s.speed<=RUN_SPEED+.01);});
test('reversing direction responds within a third of a second',()=>{const s=running();s.vz=-90;s.speed=90;advance(s,{backward:true},.3);assert.ok(s.vz>0);});
test('small sidewalk steps stay grounded, drops resume gravity',()=>{const base=createCollider();const c={...base,terrain:(x)=>({height:x>=0?.16:0,grip:1,kind:'sidewalk'}),surface:(x)=>x>=0?.16:0};const s=running();s.x=-.1;s.vx=12;advance(s,{right:true},.03,c);assert.equal(s.grounded,true);assert.equal(s.y,.16);s.vx=-12;advance(s,{left:true},.1,c);assert.ok(s.y>=0&&s.y<=.16);});
test('ground grip changes steering response while airborne control stays limited',()=>{const a=running(),b=running();a.vz=b.vz=-70;const lowGrip={...empty,terrain:()=>({height:0,grip:.45,kind:'grass'})};advance(a,{right:true},.08);advance(b,{right:true},.08,lowGrip);assert.ok(a.vx>b.vx+10);});
test('steering is consistent across render timestep sizes',()=>{const a=running(),b=running();a.vz=b.vz=-80;for(let i=0;i<30;i++)stepWorld(a,{right:true},1/30);for(let i=0;i<120;i++)stepWorld(b,{right:true},1/120);assert.ok(Math.hypot(a.x-b.x,a.z-b.z)<.2);assert.ok(Math.abs(a.speed-b.speed)<.1);});

test('releasing boost preserves momentum and decelerates gradually',()=>{const s=running();s.vz=-200;s.speed=200;stepWorld(s,{forward:true},1/120);assert.ok(s.speed>190&&s.speed<200);});
test('jump buffering fires just after landing',()=>{const s=running();s.grounded=false;s.y=.004;s.vy=-1;stepWorld(s,{jump:true},1/120);assert.equal(s.grounded,true);stepWorld(s,{},1/120);assert.equal(s.grounded,false);assert.ok(s.vy>6);});
test('a brief ledge grace period permits jumping without a midair double jump',()=>{const s=running();const ledge={...empty,surface:x=>x<0?1:0};s.x=-.01;s.y=1;s.vx=10;stepWorld(s,{right:true},1/120,ledge);assert.equal(s.grounded,false);stepWorld(s,{right:true,jump:true},1/120,ledge);assert.ok(s.vy>6);const vy=s.vy;stepWorld(s,{right:true,jump:true},1/120,ledge);assert.ok(s.vy<vy);});

test('street fixtures block movement but do not start wall runs',()=>{const fixture=createCollider([{height:4,wallRunnable:false,polygon:[[20,-3],[21,-3],[21,3],[20,3]]}]);const s=running();s.x=18;s.vx=45;s.y=1;s.grounded=false;advance(s,{right:true},.1,fixture);assert.equal(s.wallRunning,false);assert.ok(s.x<20);});

test('releasing jump produces a shorter hop than holding it',()=>{const a=running(),b=running();let short=0,full=0;for(let i=0;i<180;i++){stepWorld(a,{jump:i===0,jumpHeld:i<5},1/120);stepWorld(b,{jump:i===0,jumpHeld:true},1/120);short=Math.max(short,a.y);full=Math.max(full,b.y);}assert.ok(short<full*.7);assert.ok(full>2.2);assert.equal(a.grounded,true);assert.equal(b.grounded,true);});
test('air steering redirects a fast jump without adding speed',()=>{const s=running();s.vz=-90;s.speed=90;s.y=3;s.grounded=false;advance(s,{right:true},.2);assert.ok(s.vx>20);assert.ok(s.speed<92);assert.ok(s.vz< -40);});
test('released jump cuts upward velocity only once and cannot double jump',()=>{const s=running();stepWorld(s,{jump:true,jumpHeld:true},1/120);stepWorld(s,{jumpHeld:false},1/120);const cut=s.vy;stepWorld(s,{jumpHeld:false},1/120);assert.ok(s.vy>cut-.2);stepWorld(s,{jump:true,jumpHeld:true},1/120);assert.ok(s.vy<cut);});
